Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/03/2025
Var
// Seção de Declarações das variáveis

nome: caractere


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval("Digite seu nome por favor:")
leia(nome)
escreval("Seu nome é: ",nome)

Fimalgoritmo